services:
  backend:
    image: ghcr.io/noahkiss/feeds.fun/ffun-backend:latest

    command:
      - /bin/bash
      - -c
      - |
        poetry run ffun migrate
        echo "migrations successed"
        poetry run uvicorn ffun.application.application:app --host 0.0.0.0 --port 8000 --workers 1 --reload

    volumes:
      - ${PWD}/ffun:/repository
      - ${PWD}/.env:/repository/.env
      - ${PWD}/.configs:/repository/.configs
      - ${PWD}/feeds_collections:/repository/feeds_collections

    environment:
      FFUN_ENABLE_API: "${FFUN_ENABLE_API:-True}"
      FFUN_ENVIRONMENT: "prod"
      FFUN_ORIGINS: "*"
      FFUN_POSTGRESQL_HOST: "127.0.0.1"
      FFUN_POSTGRESQL_PORT: 5432
      FFUN_POSTGRESQL_USER: "ffun"
      FFUN_POSTGRESQL_PASSWORD: "ffun"
      FFUN_POSTGRESQL_DATABASE: "ffun"
      FFUN_AUTH_SUPERTOKENS_COLLECTION_URI: "http://127.0.0.1:3567"

    ports:
      - "8000:8000"

  backend-worker:
    image: ghcr.io/noahkiss/feeds.fun/ffun-backend:latest
    command: poetry run ffun workers --librarian --loader
    volumes:
      - ${PWD}/ffun:/repository
      - ${PWD}/.env:/repository/.env
      - ${PWD}/.configs:/repository/.configs
      - ${PWD}/tags_quality_base:/repository/tags_quality_base
      - ${PWD}/feeds_collections:/repository/feeds_collections
      - ${PWD}/changes:/repository/changes
      - ${PWD}/CHANGELOG.md:/repository/CHANGELOG.md
    environment:
      FFUN_ENABLE_SENTRY: "${FFUN_ENABLE_SENTRY:-False}"
      FFUN_SENTRY__DSN: "${FFUN_SENTRY__DSN:-not-specified}"
      FFUN_FEEDS_COLLECTIONS_COLLECTION_CONFIGS: "${FFUN_FEEDS_COLLECTIONS_COLLECTION_CONFIGS-}"

  frontend:
    image: ghcr.io/noahkiss/feeds.fun/ffun-frontend:latest

    depends_on:
      backend:
        condition: service_started

    command: "npm run dev -- --host 0.0.0.0"

    volumes:
      - ${PWD}/site/src:/repository/src

    environment:
      VITE_FFUN_AUTH_MODE: "${FFUN_AUTH_MODE-single_user}"
      VITE_FFUN_ENABLE_SENTRY: "${FFUN_ENABLE_SENTRY:-False}"
      VITE_FFUN_SENTRY_DSN: "${FFUN_SENTRY__DSN:-not-specified}"

      VITE_FFUN_PLAUSIBLE_ENABLED: "${FFUN_PLAUSIBLE_ENABLED:-False}"
      VITE_FFUN_PLAUSIBLE_DOMAIN: "${FFUN_PLAUSIBLE_DOMAIN:-localhost}"
      VITE_FFUN_PLAUSIBLE_SCRIPT: "${FFUN_PLAUSIBLE_SCRIPT:-not-specified}"

      VITE_FFUN_TRACK_EVENTS: "true"

      VITE_FFUN_APP_DOMAIN: localhost
      VITE_FFUN_APP_PORT: 5173

    ports:
      - "5173:5173"
