name: Build and Push Docker Images

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read
  packages: write

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Backend image
        uses: docker/build-push-action@v6
        id: build-and-push-backend
        with:
          context: .
          file: ./docker/prod/backend/Dockerfile
          push: true
          platforms: linux/amd64, linux/arm64
          tags: |
            ghcr.io/${{ github.repository }}/ffun-backend:latest
            ghcr.io/${{ github.repository }}/ffun-backend:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Build and push Frontend image
        uses: docker/build-push-action@v6
        id: build-and-push-frontend
        with:
          context: .
          file: ./docker/prod/frontend/Dockerfile
          push: true
          platforms: linux/amd64, linux/arm64
          tags: |
            ghcr.io/${{ github.repository }}/ffun-frontend:latest
            ghcr.io/${{ github.repository }}/ffun-frontend:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Build and push Frontend-Easy image
        uses: docker/build-push-action@v6
        id: build-and-push-frontend-easy
        with:
          context: .
          file: ./docker/prod/frontend-easy/Dockerfile
          push: true
          platforms: linux/amd64, linux/arm64
          tags: |
            ghcr.io/${{ github.repository }}/ffun-frontend-easy:latest
            ghcr.io/${{ github.repository }}/ffun-frontend-easy:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Image Digest
        run: |
          echo "Pushed backend image digest: ${{ steps.build-and-push-backend.outputs.digest }}"
          echo "Pushed frontend image digest: ${{ steps.build-and-push-frontend.outputs.digest }}"
          echo "Pushed frontend-easy image digest: ${{ steps.build-and-push-frontend-easy.outputs.digest }}"
